# Generated by Django 2.1.7 on 2019-05-06 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.SlugField(max_length=300)),
                ('short', models.SlugField()),
            ],
        ),
    ]
