# Generated by Django 2.1.7 on 2019-05-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shortener', '0002_auto_20190506_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='short',
            field=models.CharField(max_length=50),
        ),
    ]
